df <- read.csv('RATING 5.csv')
library(tm)
library(syuzhet)
sent.value<-get_sentiment(word.df)
word.df<-as.vector(df$Review)
class(word.df)
sent.value<-cbind(df,sent.value)
emotion.df <- get_nrc_sentiment(word.df)
class(word.df)
sent.value<-cbind(df,emotion.df)
jk<-cbind(sent.value,emotion.df)
